defaults:
  - policy: em_sym_bin
  - data_loader: halu_dialogue_bin
  - neural_net: two_layer_mlp
  # - override hydra/launcher: joblib
  - _self_

main:
  seed_split: 42069
  data_split: 'train'
  use_joblib_seeds: False

eval:
  epoch: ${main.eval.epoch}