name: "AvgSSLPredsContextVec"
params:
  lr: 1e-3
  weight_decay: 1e-4
  max_grad_steps: 1000
  use_joblib_fit: False
  eval_interval: 50
  patience: 200 # if no improvement in patience/eval_interval evals, stop training
  seed: 42
  lr_scheduler_type: 'constant'
  folds: 5
