name: AvgSSLPredsLM
params:
  model_dir: 'exp/pew_lm'
  lr: 1e-4
  weight_decay: 0.0
  gradient_accumulation_steps: 1
  num_warmup_steps: 0.03
  max_grad_steps: 5000
  lr_scheduler_type: 'cosine'
  log_interval: 100
  eval_interval: 500
  batch_size: 16
  probs: False