name: "LMGroundTruth"
params:
  model_dir: 'exp/lm_gt'
  lr: 1e-4
  weight_decay: 0.0
  gradient_accumulation_steps: 1
  num_warmup_steps: 0.03
  num_train_epochs: 10
  lr_scheduler_type: 'cosine'
  log_interval: 100
  batch_size: 16
